[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "vite"
  port = 5173
  targetPort = 5173
  framework = "vite"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."generate-sitemap"]
  schedule = "0 0 */7 * *" # Every 7 days at midnight UTC

